In [53]:
# 導入必要的模組
import os
import json
import pandas as pd
import re
import pickle
from sklearn import preprocessing

In [40]:

def read_json_file(file):
    with open(file, 'r') as f:
        return json.load(f)
# 定義找到特定目錄中所有JSON檔案的函數
def find_json_files(directory):
    json_files = []
    for root, _, files in os.walk(directory):
        for file in files:
            if file.endswith('.json'):
                json_files.append(os.path.join(root, file))
    return json_files
def create_summary_df(directory:str):
    all_names = []
    all_summaries = []
    
    json_files = find_json_files(directory)
    for json_file in json_files:
        with open(json_file, "r", encoding="utf-8") as f:
            data = json.load(f)
        for name, summary_list in data.items():
            all_names.extend([name] * len(summary_list))
            all_summaries.extend(summary_list)

    summary_df = pd.DataFrame({"name": all_names, "summary": all_summaries})
    return summary_df

In [41]:
directory = "G:\共用雲端硬碟\FBI_Intern\content" # 您的資料夾路徑
summary_df = create_summary_df(directory)
summary_df = summary_df[['name', 'summary']]
summary_df.head()

      name                                            summary
0  誠品信義旗艦店  誠品信義店開幕於2006年1月1日，位於信義計畫區菁華區位，連通市政府捷運站，具有絕佳立地條...
1  誠品信義旗艦店  ... 文化店; 誠品生活竹北遠百店; 誠品酒窖南西店-Nan-Xi; 誠品生活時光–內湖瑞...
2  誠品信義旗艦店  2021年11月15日 — 2006年開幕的誠品信義旗艦店擁有八層樓的廣大空間，從低樓層的美...
3  誠品信義旗艦店  即使香港已經開設誠品書店，不少遊客到臺灣時還是會到當地的誠品潮聖，不但因為店面更大貨物更齊全...
4  誠品信義旗艦店  誠品以「人文、藝術、創意、生活」為核心價值，由推廣閱讀出發，致力在書與非書之間複合創新，發展...

In [42]:
summary_df = summary_df.drop_duplicates()
# 將DataFrame儲存為Pickle檔案
with open('G:\共用雲端硬碟\FBI_Intern\summary.pkl', 'wb') as f:
    pickle.dump(summary_df, f)

In [55]:
summary_df.to_csv('G:\共用雲端硬碟\FBI_Intern\summary.csv', index=False, encoding='utf-8-sig')

 讀取貼好標籤資料

In [48]:
label = pd.read_excel("G:\共用雲端硬碟\FBI_Intern\merchant_top10000.xlsx")
label = label[['merchant_cleasing_tag','class1']]
label = label[label['class1'].notnull()]

In [49]:
label

    merchant_cleasing_tag  class1
0                 momo購物網      網購
1                    統一超商  超商超市量販
2              優食台灣股份有限公司    外送平台
3               foodpanda    外送平台
4                    樂購蝦皮      網購
..                    ...     ...
395                utaggo    交通汽修
396                大九九大賣場  超商超市量販
397                   新光產      保險
398              漢神名店百貨股份      百貨
414                    茶聚      餐飲

[384 rows x 2 columns]

In [52]:
data = pd.merge(summary_df,label,how='left',left_on='name',right_on='merchant_cleasing_tag')

,name,summary,merchant_cleasing_tag,class1
0,誠品信義旗艦店,誠品信義店開幕於2006年1月1日，位於信義計畫區菁華區位，連通市政府捷運站，具有絕佳立地條...,誠品信義旗艦店,百貨
1,誠品信義旗艦店,... 文化店; 誠品生活竹北遠百店; 誠品酒窖南西店-Nan-Xi; 誠品生活時光–內湖瑞...,誠品信義旗艦店,百貨
2,誠品信義旗艦店,2021年11月15日 — 2006年開幕的誠品信義旗艦店擁有八層樓的廣大空間，從低樓層的美...,誠品信義旗艦店,百貨
3,誠品信義旗艦店,即使香港已經開設誠品書店，不少遊客到臺灣時還是會到當地的誠品潮聖，不但因為店面更大貨物更齊全...,誠品信義旗艦店,百貨
4,誠品信義旗艦店,誠品以「人文、藝術、創意、生活」為核心價值，由推廣閱讀出發，致力在書與非書之間複合創新，發展...,誠品信義旗艦店,百貨
...,...,...,...,...
12738,魚中魚,"魚中魚的定位就是要做全國最大的全方位水族寵物用品賣場,以寬廣、明亮、整潔的大坪數購物空間,給...",魚中魚,其他
12739,魚中魚,"寵物線上購物平臺,毛孩線上購物,商品包含各大品牌寵物飼料:(皇家、希爾思),處方飼料、寵物百...",魚中魚,其他
12740,魚中魚,2022年4月25日 — 寵物水族商品一應俱全指定犬貓飼料買一送一國際品牌特惠下殺68折起....,魚中魚,其他
12741,魚中魚,魚中魚貓狗水族-北屯店. 電話：04-22478866. 地址：臺中市北屯區文心路四段319...,魚中魚,其他
12742,魚中魚,中彰投以北活動型錄-寵物用品、飼料、水族用品、貓狗鼠兔活體、寵物美容、寵物醫療、寵物住宿、觀...,魚中魚,其他

做label encoding

In [59]:
le = preprocessing.LabelEncoder()
data['integer_labels'] = le.fit_transform(data['class1'])
data

,name,summary,class1,integer_labels
0,誠品信義旗艦店,誠品信義店開幕於2006年1月1日，位於信義計畫區菁華區位，連通市政府捷運站，具有絕佳立地條...,百貨,14
1,誠品信義旗艦店,... 文化店; 誠品生活竹北遠百店; 誠品酒窖南西店-Nan-Xi; 誠品生活時光–內湖瑞...,百貨,14
2,誠品信義旗艦店,2021年11月15日 — 2006年開幕的誠品信義旗艦店擁有八層樓的廣大空間，從低樓層的美...,百貨,14
3,誠品信義旗艦店,即使香港已經開設誠品書店，不少遊客到臺灣時還是會到當地的誠品潮聖，不但因為店面更大貨物更齊全...,百貨,14
4,誠品信義旗艦店,誠品以「人文、藝術、創意、生活」為核心價值，由推廣閱讀出發，致力在書與非書之間複合創新，發展...,百貨,14
...,...,...,...,...
12738,魚中魚,"魚中魚的定位就是要做全國最大的全方位水族寵物用品賣場,以寬廣、明亮、整潔的大坪數購物空間,給...",其他,5
12739,魚中魚,"寵物線上購物平臺,毛孩線上購物,商品包含各大品牌寵物飼料:(皇家、希爾思),處方飼料、寵物百...",其他,5
12740,魚中魚,2022年4月25日 — 寵物水族商品一應俱全指定犬貓飼料買一送一國際品牌特惠下殺68折起....,其他,5
12741,魚中魚,魚中魚貓狗水族-北屯店. 電話：04-22478866. 地址：臺中市北屯區文心路四段319...,其他,5
12742,魚中魚,中彰投以北活動型錄-寵物用品、飼料、水族用品、貓狗鼠兔活體、寵物美容、寵物醫療、寵物住宿、觀...,其他,5

輸出label encoding 對照表

In [60]:
# Creating a label encoding mapping table for the 'class1' column
label_encoding_mapping = pd.DataFrame({
    'class1': label_encoder.classes_,
    'class1_encoded': range(len(label_encoder.classes_))
})

# Displaying the mapping table
label_encoding_mapping

     class1  class1_encoded
0        3C               0
1      一般消費               1
2      一般購物               2
3      交通汽修               3
4        保險               4
5        其他               5
6        加油               6
7      外送平台               7
8      家居修繕               8
9        捐款               9
10     教育學費              10
11   數位影音串流              11
12       旅遊              12
13     生活繳費              13
14       百貨              14
15       網購              15
16   超商超市量販              16
17  運動/休閒娛樂              17
18  醫療保健/美容              18
19       餐飲              19

In [61]:
with open('G:\共用雲端硬碟\FBI_Intern\label_encoding_mapping.pkl', 'wb') as f:
    pickle.dump(label_encoding_mapping, f)

In [63]:
label_encoding_mapping.to_csv('G:\共用雲端硬碟\FBI_Intern\label_encoding_mapping.csv', index=False, encoding='utf-8-sig')

In [64]:
label_encoding_mapping

     class1  class1_encoded
0        3C               0
1      一般消費               1
2      一般購物               2
3      交通汽修               3
4        保險               4
5        其他               5
6        加油               6
7      外送平台               7
8      家居修繕               8
9        捐款               9
10     教育學費              10
11   數位影音串流              11
12       旅遊              12
13     生活繳費              13
14       百貨              14
15       網購              15
16   超商超市量販              16
17  運動/休閒娛樂              17
18  醫療保健/美容              18
19       餐飲              19

In [ ]:
# 定義一個函數來檢查欄位長度
def check_lengths(item):
    if isinstance(item, dict):
        for key, value in item.items():
            if isinstance(value, (list, dict)):
                print(f"欄位 {key} 的長度：{len(value)}")
                check_lengths(value) # 遞迴處理嵌套結構

# 檢查所有欄位的長度
if isinstance(data, list):
    for item in data:
        check_lengths(item)
elif isinstance(data, dict):
    check_lengths(data)